quarkus.application.name=p1-polaris-gateway
quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=p1_gateway
quarkus.datasource.password=p1_gateway
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:55432/p1_gateway
quarkus.datasource.devservices.enabled=false
quarkus.datasource.health.enabled=true

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.otel.sdk.disabled=true

polaris.catalog.url=http://polaris:8181
polaris.catalog.client-id=root
polaris.catalog.client-secret=s3cr3t

gateway.s3.endpoint=http://minio:9000
gateway.s3.access-key-id=polaris_root
gateway.s3.secret-access-key=polaris_pass
gateway.s3.region=us-east-1
