CREATE TABLE catalog_commits (
  commit_id varchar(128) PRIMARY KEY,
  catalog_id varchar(255) NOT NULL,
  parent_commit_id varchar(128),
  author varchar(255) NOT NULL,
  message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  operation_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  index_id varchar(128),
  source_ref varchar(255),
  request_id varchar(255),
  CONSTRAINT catalog_commits_parent_fk
    FOREIGN KEY (parent_commit_id) REFERENCES catalog_commits(commit_id)
);

CREATE TABLE catalog_refs (
  catalog_id varchar(255) NOT NULL,
  ref_name varchar(255) NOT NULL,
  ref_type varchar(32) NOT NULL,
  head_commit_id varchar(128),
  policy_id varchar(128),
  deleted boolean NOT NULL DEFAULT false,
  created_by varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  version bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (catalog_id, ref_name),
  CONSTRAINT catalog_refs_type_check CHECK (ref_type IN ('BRANCH', 'TAG')),
  CONSTRAINT catalog_refs_head_fk
    FOREIGN KEY (head_commit_id) REFERENCES catalog_commits(commit_id)
);

CREATE TABLE catalog_content_values (
  value_id varchar(128) PRIMARY KEY,
  catalog_id varchar(255) NOT NULL,
  content_id varchar(128) NOT NULL,
  content_key varchar(1024) NOT NULL,
  content_type varchar(32) NOT NULL,
  metadata_location text,
  snapshot_id varchar(128),
  schema_id integer,
  spec_id integer,
  sort_order_id integer,
  table_uuid varchar(128),
  table_location text,
  format_version integer,
  last_sequence_number bigint,
  metadata_fingerprint varchar(256),
  metadata_summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_content_values_type_check
    CHECK (content_type IN ('ICEBERG_TABLE', 'VIEW', 'NAMESPACE', 'TOMBSTONE'))
);

CREATE TABLE catalog_commit_ops (
  commit_id varchar(128) NOT NULL,
  op_ordinal integer NOT NULL DEFAULT 0,
  content_key varchar(1024) NOT NULL,
  op_type varchar(32) NOT NULL,
  expected_value_id varchar(128),
  new_value_id varchar(128),
  old_content_key varchar(1024),
  new_content_key varchar(1024),
  PRIMARY KEY (commit_id, op_ordinal),
  CONSTRAINT catalog_commit_ops_commit_fk
    FOREIGN KEY (commit_id) REFERENCES catalog_commits(commit_id),
  CONSTRAINT catalog_commit_ops_expected_value_fk
    FOREIGN KEY (expected_value_id) REFERENCES catalog_content_values(value_id),
  CONSTRAINT catalog_commit_ops_new_value_fk
    FOREIGN KEY (new_value_id) REFERENCES catalog_content_values(value_id),
  CONSTRAINT catalog_commit_ops_type_check CHECK (op_type IN ('PUT', 'DELETE', 'RENAME', 'UNCHANGED'))
);

CREATE TABLE catalog_ref_indexes (
  index_id varchar(128) PRIMARY KEY,
  catalog_id varchar(255) NOT NULL,
  commit_id varchar(128) NOT NULL,
  parent_index_id varchar(128),
  index_kind varchar(32) NOT NULL,
  object_count bigint NOT NULL DEFAULT 0,
  stripe_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT catalog_ref_indexes_commit_fk
    FOREIGN KEY (commit_id) REFERENCES catalog_commits(commit_id),
  CONSTRAINT catalog_ref_indexes_parent_fk
    FOREIGN KEY (parent_index_id) REFERENCES catalog_ref_indexes(index_id),
  CONSTRAINT catalog_ref_indexes_kind_check CHECK (index_kind IN ('FULL', 'INCREMENTAL'))
);

CREATE TABLE catalog_content_index (
  index_id varchar(128) NOT NULL,
  namespace varchar(1024) NOT NULL,
  content_key varchar(1024) NOT NULL,
  content_id varchar(128) NOT NULL,
  value_id varchar(128) NOT NULL,
  content_type varchar(32) NOT NULL,
  deleted boolean NOT NULL DEFAULT false,
  PRIMARY KEY (index_id, content_key),
  CONSTRAINT catalog_content_index_index_fk
    FOREIGN KEY (index_id) REFERENCES catalog_ref_indexes(index_id),
  CONSTRAINT catalog_content_index_value_fk
    FOREIGN KEY (value_id) REFERENCES catalog_content_values(value_id),
  CONSTRAINT catalog_content_index_type_check
    CHECK (content_type IN ('ICEBERG_TABLE', 'VIEW', 'NAMESPACE', 'TOMBSTONE'))
);

CREATE TABLE idempotency_keys (
  "key" varchar(255) PRIMARY KEY,
  request_hash varchar(128) NOT NULL,
  status varchar(32) NOT NULL,
  response_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  CONSTRAINT idempotency_keys_status_check
    CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED'))
);

CREATE TABLE branch_locks (
  catalog_id varchar(255) NOT NULL,
  ref_name varchar(255) NOT NULL,
  lock_type varchar(64) NOT NULL,
  owner varchar(255) NOT NULL,
  expires_at timestamptz NOT NULL,
  fencing_token bigint GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY (catalog_id, ref_name, lock_type)
);

CREATE TABLE outbox_materializations (
  event_id varchar(128) PRIMARY KEY,
  catalog_id varchar(255) NOT NULL,
  target_ref varchar(255) NOT NULL,
  commit_id varchar(128) NOT NULL,
  status varchar(32) NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT outbox_materializations_commit_fk
    FOREIGN KEY (commit_id) REFERENCES catalog_commits(commit_id),
  CONSTRAINT outbox_materializations_status_check
    CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE audit_events (
  event_id varchar(128) PRIMARY KEY,
  catalog_id varchar(255) NOT NULL,
  ref_name varchar(255),
  actor varchar(255) NOT NULL,
  action varchar(128) NOT NULL,
  commit_id varchar(128),
  request_id varchar(255),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT audit_events_commit_fk
    FOREIGN KEY (commit_id) REFERENCES catalog_commits(commit_id)
);

CREATE UNIQUE INDEX catalog_refs_live_name_idx
  ON catalog_refs (catalog_id, ref_name)
  WHERE deleted = false;

CREATE INDEX catalog_commits_catalog_created_idx
  ON catalog_commits (catalog_id, created_at DESC);

CREATE INDEX catalog_content_values_catalog_key_idx
  ON catalog_content_values (catalog_id, content_key);

CREATE INDEX catalog_content_values_catalog_content_id_idx
  ON catalog_content_values (catalog_id, content_id);

CREATE INDEX catalog_commit_ops_content_key_idx
  ON catalog_commit_ops (content_key);

CREATE INDEX catalog_ref_indexes_catalog_commit_idx
  ON catalog_ref_indexes (catalog_id, commit_id);

CREATE INDEX catalog_content_index_namespace_idx
  ON catalog_content_index (index_id, namespace)
  WHERE deleted = false;

CREATE INDEX idempotency_keys_expiry_idx
  ON idempotency_keys (expires_at);

CREATE INDEX branch_locks_expiry_idx
  ON branch_locks (expires_at);

CREATE INDEX outbox_materializations_due_idx
  ON outbox_materializations (status, next_attempt_at);

CREATE INDEX audit_events_catalog_ref_created_idx
  ON audit_events (catalog_id, ref_name, created_at DESC);
